// src/types.ts
export interface GithubRepo {
  id: number | string;
  name: string;
  full_name: string;
  html_url: string;
  description?: string | null;
  stargazers_count?: number;
  language?: string | null;
  favorited: boolean;
}

export interface Favorite {
  // primary key generated by DB (string/UUID or number depending on your schema)
  id: string;

  // repo metadata
  repo_id: number;
  repo_name?: string | null;
  repo_full_name?: string | null;
  repo_html_url?: string | null;
  repo_description?: string | null;
  repo_stars?: number | null;
  repo_language?: string | null;

  // owner
  user_id: string | null;
  // created_at?: string | null;
}

export interface CreateFavoritePayload {
  repo_id: number | string;
  repo_name?: string;
  repo_full_name: string;
  repo_html_url?: string | null;
  repo_description?: string | null;
  repo_stars?: number;
  repo_language?: string | null;
}

export interface FavoritesResponse {
  favorites: Favorite[];
}
